### ISSUE TITLE
[Request] User setting for preferred wins

### ISSUE THREAD

**Issue by calli-yama** [daemitus/MiniCactpotSolver#1]
I've taken a look through the code, and saw that there's a pregenerated list for the wins. Is it possible to tweak that a bit (or enable runtime win chance calculations) to allow the user to specify which combos they'd like to go for? I noticed the plugin uses "highest pay"; I'd like to be able to customise mine so it only tries for a combo of 6, 23 or 24. Is this possible?

**Comment by daemitus** [comment]
If I understand the algo, it should always try for those unless it's not possible

**Comment by daemitus** [comment]
Since those are the highest payout
