### ISSUE TITLE
Update for 6.2

### ISSUE THREAD

**Issue by trynity** [daemitus/MiniCactpotSolver#2]
Please update the `DalamudApiLevel` to `7`, assuming that no other changes are needed.

**Comment by daemitus** [comment]
should be up shortly, if the folks can unbreak my PR

**Comment by rz-1** [comment]
hello, in case you were not aware, it is still showing as dalmundapilevel 6 here
https://github.com/goatcorp/PluginDistD17/blob/main/stable/MiniCactpotSolver/MiniCactpotSolver.json
