### ISSUE TITLE
Add back green color 

### ISSUE THREAD

**Issue by ShichiIzanagi** [daemitus/MiniCactpotSolver#8]
Can we please get the green coloring of the buttons back, as an option or something maybe? The blue really stings on the background, or at least let it be customizable. 

Its way too bright.

**Comment by MidoriKami** [comment]
The color was changed for accessibility reasons. It is logistically difficult to add a color picker.

**Comment by ShichiIzanagi** [comment]
Frustrating, wouldve been nice to get options before you changed it as its an eye sore now due to being way too bright.
